defaults:
  - evolver: circle_packing_shinka
  - api_platforms@api_platforms.ollama_qwen35_27b: ollama_qwen35_27b
  - api_platforms@api_platforms.ollama_gemma4_26b: ollama_gemma4_26b
  - api_platforms@api_platforms.ollama_nemotron_cascade_2_30b: ollama_nemotron_cascade_2_30b
  - experiments@experiments.unit_square_26: circle_packing_shinka/unit_square_26
  - _self_

seed: 42
deterministic: false
mode: evolve
device: cpu
precision: fp32
num_workers: 0

resources:
  evaluation:
    gpu_ranks: []
    cpu_parallel_jobs: 20

paths:
  data_root: ${oc.env:AIFS_DATA_ROOT,./data}
  stats_root: ${oc.env:AIFS_STATS_ROOT,./stats}
  runs_root: ${oc.env:AIFS_RUNS_ROOT,./runs}
  candidate_results_dirname: results
  population_root: ${oc.env:POP_ROOT,./populations/circle-packing}
  api_platform_runtime_root: ${oc.env:API_PLATFORM_RUNTIME_ROOT,./.api_platform_runtime_circle-packing}
  ollama_cache_root: ${oc.env:OLLAMA_MODELS,./ollama_cache}


api_platforms:
  ollama_qwen35_27b:
    base_url: ${oc.env:OLLAMA_QWEN35_27B_BASE_URL,http://127.0.0.1:12436/api}
    gpu_ranks: [2]
    max_concurrency: 3
    stage_options:
      design:
        think: false
        max_output_tokens: 6000
      implementation:
        think: false
        max_output_tokens: 6000
      repair:
        think: false
        max_output_tokens: 6000
      novelty_check:
        think: false
        max_output_tokens: 6000

  ollama_gemma4_26b:
    base_url: ${oc.env:OLLAMA_GEMMA4_26B_BASE_URL,http://127.0.0.1:12435/api}
    gpu_ranks: [1]
    max_concurrency: 3
    stage_options:
      design:
        think: false
        max_output_tokens: 6000
      implementation:
        think: false
        max_output_tokens: 6000
      repair:
        think: false
        max_output_tokens: 6000
      novelty_check:
        think: false
        max_output_tokens: 6000

  ollama_nemotron_cascade_2_30b:
    base_url: ${oc.env:OLLAMA_NEMOTRON_CASCADE_2_30B_BASE_URL,http://127.0.0.1:12434/api}
    gpu_ranks: [0]
    max_concurrency: 3
    stage_options:
      design:
        think: false
        max_output_tokens: 6000
      implementation:
        think: false
        max_output_tokens: 6000
      repair:
        think: false
        max_output_tokens: 6000
      novelty_check:
        think: false
        max_output_tokens: 6000

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: hydra
  job:
    chdir: false
